### ISSUE TITLE
[FEATURE][Checklist][Entity]

### ISSUE THREAD

**Issue by devJaem** [devJaem/sktrello#1]
---

# Issue: 🐵FEATURE

## 🎈Description

체크리스트 기본 엔티티 설계
## 🎹Progress
- [x] ERD를 참고하여 엔티티설계
- [x] createdat, updatedat 컬럼 설계
- [x] softdelete 구현을 위한 컬럼 설계
